version: '3.4'

services:

  ocelotapibase:
    image: ocelotapibaseimg
    ports:
        - "9305:80"
    build:
      context: .
      dockerfile: OcelotApiBase/Dockerfile
    networks: 
      - custom-network  
    container_name: ocelotapibase

  dateservice:
    image: dateserviceimg
    networks: 
      - custom-network
    build:
      context: .
      dockerfile: DateService/Dockerfile
    container_name: dateservice

  consul-server: 
    image: consul:latest
    networks: 
      - custom-network
    ports: 
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      CONSUL_LOCAL_CONFIG: "{\"service\":{\"Name\": \"date\",\"Address\": \"dateservice\",\"Port\": 80}}"
    command: "agent -server -data-dir /tmp/consul -config-dir /consul/config -bootstrap-expect 1 -ui -client 0.0.0.0"
    container_name: consul

networks:
  custom-network:
    driver: bridge

    
